### PR TITLE
Update with new package skeleton

### PR DESCRIPTION
**Pull request by lkdvos**
This PR provides an intermediate update for the ongoing work of getting a good package skeleton.

### CODE REVIEW

**Comment by lkdvos** [comment]
Small FYI that the codecov will continue complaining until a token is added to the secrets of the repository, and that has been properly set up. I don't have the rights to access this however.

**Comment by mtfishman** [comment]
> Small FYI that the codecov will continue complaining until a token is added to the secrets of the repository, and that has been properly set up. I don't have the rights to access this however.

How would I do that, and/or how would I give you access to do that?

**Comment by mtfishman** [comment]
The [CI.yml](https://github.com/ITensor/UnspecifiedTypes.jl/blob/b160fd1fe9a0c03192d677224e262c005840f0a0/.github/workflows/CI.yml) workflow needs to be deleted.

**Comment by lkdvos** [comment]
Ok, this seems to now have fixed the remaining issues with the codecov actions, and is ready to merge + register from my end.

**Pull request merged**
